config/routes.rb
GenerUs::Application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "methodology" => "pages#methodology"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def methodology
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<div class='navbar navbar-default navbar-fixed-top'>
  <div class="container-fluid">
    <div class='container'>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logosmall.png'), root_path, class: "navbar-brand" %>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Buy Responsibly', '#' %></li>
        <li><%= link_to 'Give Responsibly', '#' %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">About<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "How we review organizations", methodology_path %></li>
            <li class="divider"></li>
            <li><a href="#">Our story</a></li>
            <li><a href="#">Our mission</a></li>
            <li><a href="#">Meet the team</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contact<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Request a review</a></li>
            <li class="divider"></li>
            <li><a href="#">Feedback</a></li>
            <li><a href="#">Careers</a></li>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li> 
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else %>
           <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GenerUs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
<div class="body">

	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info center") %>
	<% end %>

	<%= yield %>
	
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="mainpage">

	<div class="container center">
		<h1 class="brand-color">GenerUs</h1>
		<% if user_signed_in? %>
	          # do something
	     <% else %>
		<%= link_to "log in", new_user_session_path, class:"btn btn-default center" %>
		<%= link_to "sign up", new_user_registration_path, class:"btn btn-default center" %>
		<% end %>


	<p><br>to learn more about us, click <%= link_to "this", about_path %>
	</div>
</div>

app/views/pages/methodology.html.erb
<div class="container center">
	<h1>Corporate accountability.</h1>
	<h2><span class="muted">How we grade for-profit corporations.</span></h1>
	<p class="center">Our market research team pours over SEC filings, press releases, public information, and anything else that we can get our hands on in order to analyze for profit companies based on a host of factors. These factors boil down to three core groups: transparency, sustainability and humanity. </p>

<hr>
<div class="containter">
	<div class="row">
		<div class="col-lg-4 center">
			<h3>Transparency</h3>
			<p>One of the primary goals at <span style="color:#f39c12">GenerUs</span>, is the promotion of corporate transparency. We want you to know what kinds of decisions are being made by the companies you buy from, and we want this to be as easy as possible to discover. We look at what information is available, and how accessible it is. We examine this information in light of companies' identities, and what they hold themselves out to be.
			<p><button type="button" class="btn btn-default center">Read more &raquo;</a></p>
		</div>
		<div class="col-lg-4 center">
			<h3>Sustainability</h3>
			<p>At <span style="color:#f39c12">GenerUs</span>, we realize the importance of promoting sustainability within consumer markets. We research the efforts being made by companies to minimize their ecological footprint. This means looking for LEED certifications, recycled and upcycled resources used in production and RD that companies are putting toward clean technology.
			<p><button type="button" class="btn btn-default center">Read more &raquo;</a></p>
		</div>
		<div class="col-lg-4 center">
			<h3>Humanity</h3>
			<p>We want you to know how the companies that you buy from are treating the humans that they interact with. This means that here at <span style="color:#f39c12">GenerUs</span>, we scour the inter-web for data on employee & executive compensation, scrutinize supply chains, and find out how companies are giving back to the people in their communities.
			<p><button type="button" class="btn btn-default center">Read more &raquo;</a></p>
		</div>
	</div>
<hr>
<h1>Transparency. Getting under their skin.</h1>

<hr>

<h1>Humanity. Working for one another.</h1>

<p>We want to know how companies treat real, live, actual people. The people that they employ, the people from whom they buy materials and products, and the people in their communities. There are three areas we look to in order to asses a score for this category: </p>

<div class="containter">
	<h2>Employee benefits. <span class="muted">How do they treat their own?</span></h2>

	<p>We examine the employee compensation all the way up the ladder, from service employees, to executives. We want you to know how companies value all of their employees; relative to one another, relative to industry and nationwide averages. We want you to be able to consume knowing that your products were made by employees making a living wage. We also look to employee benefits. Does the company offer health insurance? Life insurance? What about employees with disabilities? All of these questions matter, and we think that you care.</p>

</div>